siwecos.settings:
  type: config_object
  mapping:
    api_url:
      type: uri
      label: 'API URL'
    api_token:
      type: string
      label: 'API token'
    domain:
      type: uri
      label: 'Domain'
    domain_token:
      type: string
      label: 'Domain token'
    email:
      type: mail
      label: 'Email'
    password:
      type: string
      label: 'Password'

block.settings.siwecos_seal:
  type: block_settings
  label: 'Siwecos seal'
  mapping:
    date_format:
      type: string
      label: Date format
    height:
      type: integer
      label: Height
    width:
      type: integer
      label: Width
